CREATE DATABASE BaiTapLonWeb
USE BaiTapLonWeb
GO
CREATE TABLE tblUser
( 
	MaUS INT PRIMARY KEY IDENTITY(1,1),
	UserName VARCHAR(50) NOT NULL UNIQUE,
	Pass VARCHAR(50) NOT NULL,
	LoaiUser BIT NOT NULL 
)
CREATE TABLE tblTrangCN
(
	MaTCN INT PRIMARY KEY IDENTITY(1,1),
	NameTCN NVARCHAR(100) NOT NULL,
	MaUS INT NOT NULL
)
ALTER TABLE dbo.tblTrangCN ADD CONSTRAINT FK_user_trangCN FOREIGN KEY(MaUS)	REFERENCES dbo.tblUser(MaUS)
CREATE TABLE tblChuDe
(
	MaChuDe INT PRIMARY KEY IDENTITY(1,1),
	TenChuDe NVARCHAR(50) NOT NULL
)
CREATE TABLE tblBaiViet(
	MaBV INT PRIMARY KEY IDENTITY(1,1),
	TieuDe NVARCHAR(256) NOT NULL,
	NoiDung NVARCHAR(1000) NOT NULL,
	linkAnh NVARCHAR(1000),
	SoLike INT,
	SoComment INT,
	MaChuDe INT NOT NULL,
	MaTCN INT NOT NULL
)
ALTER TABLE dbo.tblBaiViet ADD CONSTRAINT FK_trangCN_BaiViet FOREIGN KEY(MaTCN)	REFERENCES dbo.tblTrangCN(MaTCN), 
CONSTRAINT FK_Chude_BaiViet FOREIGN KEY(MaChuDe) REFERENCES dbo.tblChuDe(MaChuDe)
CREATE TABLE tblComment(
	MaCM INT PRIMARY KEY IDENTITY(1,1),
	MaTCN INT NOT NULL,
	NoiDung NVARCHAR(1000) NOT NULL,
	MaBV INT NOT NULL
)
ALTER TABLE dbo.tblComment ADD CONSTRAINT FK_Comment_BaiViet FOREIGN KEY(MaBV) REFERENCES dbo.tblBaiViet(MaBV),
CONSTRAINT FK_Comment_TCN FOREIGN KEY(MaTCN) REFERENCES dbo.tblTrangCN(MaTCN)
CREATE TABLE tblLike(
	MaLike INT PRIMARY KEY IDENTITY(1,1),
	icon NVARCHAR(1000) NOT NULL,
	MaTCN INT NOT NULL,
	MaBV INT NOT NULL
)
ALTER TABLE dbo.tblLike ADD CONSTRAINT FK_Like_BaiViet FOREIGN KEY(MaBV) REFERENCES dbo.tblBaiViet(MaBV),
CONSTRAINT FK_Like_TCN FOREIGN KEY(MaTCN) REFERENCES dbo.tblTrangCN(MaTCN)
GO	
Create TRIGGER AddComment 
ON dbo.tblComment
FOR INSERT
AS
BEGIN
	DECLARE @MaBV INT 
	SELECT @MaBV=Inserted.MaBV 
	FROM Inserted
	UPDATE dbo.tblBaiViet
	SET SoComment =SoComment+1 
	WHERE MaBV=@MaBV
END
GO	
CREATE TRIGGER removeComment 
ON dbo.tblComment
FOR DELETE
AS
BEGIN
	DECLARE @MaBV INT 
	SELECT @MaBV=Deleted.MaBV 
	FROM Deleted
	UPDATE dbo.tblBaiViet
	SET SoComment =SoComment-1
	WHERE MaBV=@MaBV
END
go
Create TRIGGER AddLike 
ON dbo.tblLike
FOR INSERT
AS
BEGIN
	DECLARE @MaBV INT 
	SELECT @MaBV=Inserted.MaBV 
	FROM Inserted
	UPDATE dbo.tblBaiViet
	SET SoLike =SoLike+1 
	WHERE MaBV=@MaBV
END
GO	
Create TRIGGER removeLike
ON dbo.tblLike
FOR DELETE
AS
BEGIN
	DECLARE @MaBV INT 
	SELECT @MaBV=Deleted.MaBV 
	FROM Deleted
	UPDATE dbo.tblBaiViet
	SET SoLike =SoLike-1 
	WHERE MaBV=@MaBV
END
GO	
CREATE TRIGGER upBaiViet
ON dbo.tblBaiViet
FOR INSERT
AS
BEGIN
	DECLARE @MaBV INT 
	SELECT @MaBV=Inserted.MaBV 
	FROM Inserted
	UPDATE dbo.tblBaiViet
	SET SoLike =0,SoComment=0
	WHERE MaBV=@MaBV
END
GO
create TRIGGER deletetblBV
ON dbo.tblBaiViet
INSTEAD OF DELETE
AS
BEGIN
    DECLARE @MaBV INT
	SELECT @MaBV = Deleted.MaBV
	FROM Deleted
	DELETE dbo.tblLike
	WHERE MaBV=@MaBV
	DELETE dbo.tblComment
	WHERE MaBV=@MaBV
	DELETE dbo.tblBaiViet
	WHERE MaBV = @MaBV
END
GO
